---
global:
  isStandalone: false

image:
  repository: dogeos69/scroll-stack-contracts
  tag: deploy-f961bf3e75c7c3fec63250062e751b0aaf47fefd

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
