---
global:
  isStandalone: false

image:
  repository: shuunifra/scroll-stack-contracts
  tag: deploy-db5a12452586121c219a2d9e877fce8ef86c6eb9

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
