NAMESPACE ?= default

install:
	$(MAKE) install-scroll-monitor
	$(MAKE) install-scroll-common
	$(MAKE) install-l2-sequencer
	$(MAKE) install-coordinator-api
	$(MAKE) install-bridge-history-api
	$(MAKE) install-bridge-history-fetcher
	$(MAKE) install-chain-monitor
	$(MAKE) install-coordinator-cron
	$(MAKE) install-frontends
	$(MAKE) install-gas-oracle
	$(MAKE) install-l2-bootnode
	$(MAKE) install-l2-rpc
	$(MAKE) install-rollup-explorer-backend
	$(MAKE) install-rollup-node
	$(MAKE) install-admin-system-backend
	$(MAKE) install-admin-system-cron
	$(MAKE) install-admin-system-dashboard
	$(MAKE) install-contracts
	$(MAKE) install-balance-checker
	$(MAKE) install-l1-devnet

install-scroll-monitor:
	helm upgrade -i scroll-monitor oci://ghcr.io/scroll-tech/scroll-sdk/helm/scroll-monitor -n $(NAMESPACE) \
		--version=0.1.0 \
		--values values/scroll-monitor-production.yaml

install-scroll-common:
	helm upgrade -i scroll-common oci://ghcr.io/scroll-tech/scroll-sdk/helm/scroll-common -n $(NAMESPACE) \
		--version=0.1.0 \
		--values values/genesis.yaml

install-l2-sequencer:
	helm upgrade -i l2-sequencer-0 oci://ghcr.io/scroll-tech/scroll-sdk/helm/l2-sequencer -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/l2-sequencer-production-0.yaml

	helm upgrade -i l2-sequencer-1 oci://ghcr.io/scroll-tech/scroll-sdk/helm/l2-sequencer -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/l2-sequencer-production-1.yaml

install-coordinator-api:
	helm upgrade -i coordinator-api oci://ghcr.io/scroll-tech/scroll-sdk/helm/coordinator-api -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/coordinator-api-production.yaml \
		--values values/coordinator-api-config.yaml

install-bridge-history-api:
	helm upgrade -i bridge-history-api oci://ghcr.io/scroll-tech/scroll-sdk/helm/bridge-history-api -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/bridge-history-api-production.yaml \
		--values values/bridge-history-api-config.yaml

install-bridge-history-fetcher:
	helm upgrade -i bridge-history-fetcher oci://ghcr.io/scroll-tech/scroll-sdk/helm/bridge-history-fetcher -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/bridge-history-fetcher-production.yaml \
		--values values/bridge-history-fetcher-config.yaml

install-chain-monitor:
	helm upgrade -i chain-monitor oci://ghcr.io/scroll-tech/scroll-sdk/helm/chain-monitor -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/chain-monitor-production.yaml \
		--values values/chain-monitor-config.yaml

install-coordinator-cron:
	helm upgrade -i coordinator-cron oci://ghcr.io/scroll-tech/scroll-sdk/helm/coordinator-cron -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/coordinator-cron-production.yaml \
		--values values/coordinator-cron-config.yaml

install-frontends:
	helm upgrade -i frontends oci://ghcr.io/scroll-tech/scroll-sdk/helm/frontends -n $(NAMESPACE) \
		--version=0.1.1 \
		--values values/frontends-production.yaml \
		--values values/frontends-config.yaml

install-gas-oracle:
	helm upgrade -i gas-oracle oci://ghcr.io/scroll-tech/scroll-sdk/helm/gas-oracle -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/gas-oracle-production.yaml \
		--values values/gas-oracle-config.yaml

install-l2-bootnode:
	helm upgrade -i l2-bootnode-0 oci://ghcr.io/scroll-tech/scroll-sdk/helm/l2-bootnode -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/l2-bootnode-production-0.yaml

	helm upgrade -i l2-bootnode-1 oci://ghcr.io/scroll-tech/scroll-sdk/helm/l2-bootnode -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/l2-bootnode-production-1.yaml

install-l2-rpc:
	helm upgrade -i l2-rpc oci://ghcr.io/scroll-tech/scroll-sdk/helm/l2-rpc -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/l2-rpc-production.yaml

install-rollup-explorer-backend:
	helm upgrade -i rollup-explorer-backend oci://ghcr.io/scroll-tech/scroll-sdk/helm/rollup-explorer-backend -n $(NAMESPACE) \
		--version=0.1.1 \
		--values values/rollup-explorer-backend-production.yaml \
		--values values/rollup-explorer-backend-config.yaml

install-rollup-node:
	helm upgrade -i rollup-node oci://ghcr.io/scroll-tech/scroll-sdk/helm/rollup-node -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/rollup-node-production.yaml \
		--values values/rollup-node-config.yaml

install-admin-system-backend:
	helm upgrade -i admin-system-backend oci://ghcr.io/scroll-tech/scroll-sdk/helm/admin-system-backend -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/admin-system-backend-production.yaml \
		--values values/admin-system-backend-config.yaml

install-admin-system-cron:
	helm upgrade -i admin-system-cron oci://ghcr.io/scroll-tech/scroll-sdk/helm/admin-system-cron -n $(NAMESPACE) \
		--version=0.1.2 \
		--values values/admin-system-cron-production.yaml \
		--values values/admin-system-cron-config.yaml

install-admin-system-dashboard:
	helm upgrade -i admin-system-dashboard oci://ghcr.io/scroll-tech/scroll-sdk/helm/admin-system-dashboard -n $(NAMESPACE) \
		--version=0.1.1 \
		--values values/admin-system-dashboard-production.yaml

install-contracts:
	scrollsdk helper fund-accounts -d -f 0.2
	helm upgrade -i contracts oci://ghcr.io/scroll-tech/scroll-sdk/helm/contracts -n $(NAMESPACE) \
		--version=0.1.1 \
		--values values/contracts-production.yaml \
		--values values/scroll-common-config-contracts.yaml \
		--values values/scroll-common-config.yaml

install-balance-checker:
	helm upgrade -i balance-checker oci://ghcr.io/scroll-tech/scroll-sdk/helm/balance-checker -n $(NAMESPACE) \
		--version=0.1.1 \
		--values values/balance-checker-production.yaml \
		--values values/balance-checker-config.yaml

install-l1-devnet:
	helm upgrade -i l1-devnet oci://ghcr.io/scroll-tech/scroll-sdk/helm/l1-devnet -n $(NAMESPACE) \
		--version=0.1.3 \
		--values values/l1-devnet-production.yaml

delete:
	-helm uninstall -n $(NAMESPACE) scroll-common
	-helm uninstall -n $(NAMESPACE) l2-sequencer-0
	-helm uninstall -n $(NAMESPACE) l2-sequencer-1
	-helm uninstall -n $(NAMESPACE) coordinator-api
	-helm uninstall -n $(NAMESPACE) bridge-history-api
	-helm uninstall -n $(NAMESPACE) bridge-history-fetcher
	-helm uninstall -n $(NAMESPACE) chain-monitor
	-helm uninstall -n $(NAMESPACE) coordinator-cron
	-helm uninstall -n $(NAMESPACE) frontends
	-helm uninstall -n $(NAMESPACE) gas-oracle
	-helm uninstall -n $(NAMESPACE) l2-bootnode-0
	-helm uninstall -n $(NAMESPACE) l2-bootnode-1
	-helm uninstall -n $(NAMESPACE) l2-rpc
	-helm uninstall -n $(NAMESPACE) rollup-explorer-backend
	-helm uninstall -n $(NAMESPACE) rollup-node
	-helm uninstall -n $(NAMESPACE) admin-system-backend
	-helm uninstall -n $(NAMESPACE) admin-system-cron
	-helm uninstall -n $(NAMESPACE) admin-system-dashboard
	-helm uninstall -n $(NAMESPACE) contracts
	-helm uninstall -n $(NAMESPACE) scroll-monitor
	-helm uninstall -n $(NAMESPACE) balance-checker

delete-l1-devnet:
	helm delete -n $(NAMESPACE) l1-devnet
